### ISSUE TITLE
BTS post not showing on the News / home page

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#151]
e.g. http://www.mesophotic.org/posts/78
not showing on home or news page

**Comment by ryanbooker** [comment]
Database was still saving 't' and 'f' for bools, instead of 1 and 0. I _think_ I've fixed it.

**Comment by veronicar239** [comment]
I posted a new post (http://www.mesophotic.org/posts/79) but it appears that this issue still exists. The new post does not show up on the News/Posts page nor on the home page, but I can see it listed within the admin page.
http://www.mesophotic.org/admin/posts?page=3

**Comment by veronicar239** [comment]
Same issue for new announcement post e.g., http://www.mesophotic.org/posts/joining-forces-to-monitor-mce-bleaching/

**Comment by veronicar239** [comment]
I think this is now fixed? Not sure if @ryanbooker wants to make a note about what happened since this has been a reoccuring issue.
